/**
 * Bizarre Cafe — Supabase Client
 *
 * Provides both a standard anon client and a service-role client.
 * - anon client: for client-side / edge operations (row-level security enforced)
 * - service client: for server-side operations (bypasses RLS, use with caution)
 *
 * Re-exports the DB types generated by `supabase gen types typescript`.
 */

import { createClient, type SupabaseClient, type PostgresMeta } from '@supabase/supabase-js';
import type { Database } from './types/database.types';
import { config } from '../config';

// ─── Anon Client ──────────────────────────────────────────────────────

/** Standard Supabase client using the anon key (RLS enforced). */
export const supabase = createClient<Database>(
  config.supabaseUrl,
  config.supabaseKey,
  {
    auth: {
      persistSession: false,
      autoRefreshToken: false,
    },
    db: {
      schema: 'public',
    },
    global: {
      fetch: async (url, init?) => {
        // Inject auth headers for internal proxy calls if needed
        const headers = new Headers(init?.headers);
        headers.set('x-service-key', config.supabaseServiceRoleKey);
        return fetch(url, { ...init, headers });
      },
    },
  }
);

// ─── Service Role Client ──────────────────────────────────────────────

/**
 * Service-role client — bypasses RLS policies.
 * Use ONLY on the server side for admin operations.
 */
export const supabaseAdmin = createClient<Database>(
  config.supabaseUrl,
  config.supabaseServiceRoleKey,
  {
    auth: {
      persistSession: false,
      autoRefreshToken: false,
    },
    db: {
      schema: 'public',
    },
  }
);

// ─── Type Helpers ─────────────────────────────────────────────────────

/**
 * Type-safe query builder helper.
 * Wraps a supabase query to give proper typed results.
 */
export const query = {
  from: supabase.from.bind(supabase),
  fromAdmin: supabaseAdmin.from.bind(supabaseAdmin),
};

/**
 * Database types re-export.
 * Use these for typed row/insert/update shapes.
 *
 * Example:
 *   import type { Database } from '@/supabase/types/database.types';
 *   type RoomRow = Database['public']['Tables']['rooms']['Row'];
 *   type RoomInsert = Database['public']['Tables']['rooms']['Insert'];
 *   type RoomUpdate = Database['public']['Tables']['rooms']['Update'];
 */
export type { Database, SupabaseClient, PostgresMeta };

/** Convenience: typed SupabaseClient<Database> */
export type DbClient = SupabaseClient<Database>;
