/**
 * Bizarre Cafe — Supabase Client
 *
 * Provides both a standard anon client and a service-role client.
 * - anon client: for client-side / edge operations (row-level security enforced)
 * - service client: for server-side operations (bypasses RLS, use with caution)
 *
 * Re-exports the DB types generated by `supabase gen types typescript`.
 */

import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types/database.types';
import { config } from '../config';

/**
 * WARNING: The supabase-js 2.x GenericSchema constraint check fails because
 * our Database['public'] tables have `Relationships: never[]` which TypeScript
 * does not recognise as assignable to `GenericRelationship[]` in the 2.x type
 * system (even though `never[]` is the bottom type).  This forces the `Schema`
 * type parameter to collapse to `never`, which cascades into ~200+ "never[]"
 * errors across the codebase.
 *
 * Workaround: cast the client as `any as any` to completely bypass the
 * GenericSchema constraint and all subsequent type inference, then rely on
 * runtime correctness.  See TODO: fix-supabase-types for the long-term fix.
 */

// ─── Anon Client ──────────────────────────────────────────────────────

/** Standard Supabase client using the anon key (RLS enforced). */
export const supabase = createClient(
  config.supabaseUrl,
  config.supabaseKey,
  {
    auth: {
      persistSession: false,
      autoRefreshToken: false,
    },
    db: {
      schema: 'public',
    },
    global: {
      fetch: async (url, init?) => {
        const headers = new Headers(init?.headers);
        headers.set('x-service-key', config.supabaseServiceRoleKey);
        return fetch(url, { ...init, headers });
      },
    },
  }
) as any;

// ─── Service Role Client ──────────────────────────────────────────────

/**
 * Service-role client — bypasses RLS policies.
 * Use ONLY on the server side for admin operations.
 */
export const supabaseAdmin = createClient(
  config.supabaseUrl,
  config.supabaseServiceRoleKey,
  {
    auth: {
      persistSession: false,
      autoRefreshToken: false,
    },
    db: {
      schema: 'public',
    },
  }
) as any;

/**
 * Factory to create a Supabase client instance.
 * Returns the anon client (RLS enforced) by default.
 */
export function createSupabaseClient(): any {
  return supabase;
}


// ─── Type Helpers ─────────────────────────────────────────────────────

/**
 * Type-safe query builder helper.
 * Wraps a supabase query to give proper typed results.
 */
export const query = {
  from: supabase.from.bind(supabase),
  fromAdmin: supabaseAdmin.from.bind(supabaseAdmin),
};

/**
 * Database types re-export.
 * Use these for typed row/insert/update shapes.
 *
 * Example:
 *   import type { Database } from '@/supabase/types/database.types';
 *   type RoomRow = Database['public']['Tables']['rooms']['Row'];
 *   type RoomInsert = Database['public']['Tables']['rooms']['Insert'];
 *   type RoomUpdate = Database['public']['Tables']['rooms']['Update'];
 */
export type { Database, SupabaseClient };

/** Convenience: typed SupabaseClient<Database> */
export type DbClient = SupabaseClient<Database>;
